# Generated by Django 2.2.2 on 2019-07-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='ChapterNumber',
            field=models.IntegerField(verbose_name='章节数'),
        ),
        migrations.AlterField(
            model_name='books',
            name='KindSN',
            field=models.IntegerField(verbose_name='归类'),
        ),
        migrations.AlterField(
            model_name='books',
            name='NewOrOld',
            field=models.IntegerField(choices=[(0, '旧约'), (1, '新约')], default=0, verbose_name='新旧约'),
        ),
        migrations.AlterField(
            model_name='contents',
            name='ChapterSN',
            field=models.IntegerField(verbose_name='章'),
        ),
        migrations.AlterField(
            model_name='contents',
            name='VerseSN',
            field=models.IntegerField(verbose_name='节'),
        ),
    ]
