# Generated by Django 2.2.2 on 2019-07-12 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0002_auto_20190702_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='VolumeSN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='bible.Books', verbose_name='卷名'),
        ),
    ]
