# Generated by Django 2.2.2 on 2019-07-03 09:38

import DjangoUeditor.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='类名')),
                ('is_hiden', models.BooleanField(default=False, verbose_name='是否隐藏')),
                ('keyword', models.CharField(blank=True, max_length=10, null=True, verbose_name='类别关键词')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subs', to='news.ArticleClass', verbose_name='父类')),
            ],
            options={
                'verbose_name': '文章分类',
                'verbose_name_plural': '文章分类',
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='类名')),
                ('keyword', models.CharField(blank=True, max_length=50, null=True, verbose_name='文章关键字')),
                ('introduction', models.CharField(blank=True, max_length=200, null=True, verbose_name='简介')),
                ('image', models.ImageField(upload_to='articles/%Y/%m', verbose_name='封面图')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('detail', DjangoUeditor.models.UEditorField(default='', verbose_name='文章详情')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('is_head', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('articleclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.ArticleClass', verbose_name='分类')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
    ]
