# Generated by Django 2.2.2 on 2019-07-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190703_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='snap_nums',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
    ]
