# Generated by Django 2.2.3 on 2019-07-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20190720_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='news_type',
            field=models.IntegerField(choices=[(0, '文本无图'), (1, '普通单图'), (2, '普通多图'), (3, '图文大图'), (4, '视频')], default=0, verbose_name='内容类型'),
        ),
    ]
