# Generated by Django 2.2.3 on 2019-08-02 18:05

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinteractives',
            name='answer',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='答题内容'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinteractives',
            name='has_read',
            field=models.BooleanField(default=False, verbose_name='是否已答'),
        ),
        migrations.AlterUniqueTogether(
            name='userfavorite',
            unique_together={('user', 'fav_id', 'fav_type')},
        ),
    ]
