# Generated by Django 2.2.2 on 2019-07-03 14:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0002_auto_20190703_1455'),
        ('bible', '0002_auto_20190702_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractiveClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='分类名称')),
                ('number', models.IntegerField(default=0, verbose_name='问题数')),
                ('score', models.IntegerField(default=0, verbose_name='总分数')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '交互分类',
                'verbose_name_plural': '交互分类',
            },
        ),
        migrations.CreateModel(
            name='InteractiveMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100, verbose_name='提示消息')),
                ('message_type', models.IntegerField(choices=[(0, '其他'), (1, '正确'), (2, '错误')], default=0, verbose_name='消息类型')),
                ('show_type', models.IntegerField(choices=[(0, '默认'), (1, '气泡'), (2, '弹窗')], default=0, verbose_name='展示类型')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
        ),
        migrations.CreateModel(
            name='Interactives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='内容')),
                ('content_type', models.IntegerField(choices=[(0, '只读内容'), (1, '问题内容'), (2, '选项内容')], default=0, verbose_name='内容类型')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('background', models.ImageField(default='interactive/default.png', upload_to='interactive/%Y/%m', verbose_name='背景图')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('bible_contents', models.ManyToManyField(blank=True, null=True, to='bible.Contents', verbose_name='引用经文')),
                ('interclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactive.InteractiveClass', verbose_name='分类')),
                ('intermessage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactive.InteractiveMessage', verbose_name='提示消息')),
                ('new_contents', models.ManyToManyField(blank=True, null=True, to='news.Articles', verbose_name='引用新闻')),
                ('next_content', models.ManyToManyField(blank=True, null=True, related_name='_interactives_next_content_+', to='interactive.Interactives', verbose_name='下一个内容')),
                ('pre_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pres', to='interactive.Interactives', verbose_name='上一个内容')),
            ],
            options={
                'verbose_name': '交互内容',
                'verbose_name_plural': '交互内容',
            },
        ),
    ]
