# Generated by Django 2.2.2 on 2019-07-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interactivemessage',
            options={'verbose_name': '提示消息', 'verbose_name_plural': '提示消息'},
        ),
        migrations.AlterField(
            model_name='interactives',
            name='bible_contents',
            field=models.ManyToManyField(to='bible.Contents', verbose_name='引用经文'),
        ),
        migrations.AlterField(
            model_name='interactives',
            name='new_contents',
            field=models.ManyToManyField(to='news.Articles', verbose_name='引用新闻'),
        ),
    ]
