# Generated by Django 2.2.2 on 2019-07-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0002_auto_20190703_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactives',
            name='next_content',
            field=models.ManyToManyField(related_name='_interactives_next_content_+', to='interactive.Interactives', verbose_name='下一个内容'),
        ),
    ]
