# Generated by Django 2.2.2 on 2019-07-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0003_auto_20190703_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactives',
            name='score',
            field=models.IntegerField(default=0, verbose_name='得分'),
        ),
    ]
