# Generated by Django 2.2.2 on 2019-07-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0004_interactives_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interactives',
            name='bible_contents',
        ),
        migrations.AddField(
            model_name='interactives',
            name='bible_contents',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='引用经文'),
        ),
        migrations.RemoveField(
            model_name='interactives',
            name='new_contents',
        ),
        migrations.AddField(
            model_name='interactives',
            name='new_contents',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='引用新闻'),
        ),
        migrations.RemoveField(
            model_name='interactives',
            name='next_content',
        ),
        migrations.AddField(
            model_name='interactives',
            name='next_content',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='下一个内容'),
        ),
    ]
