# Generated by Django 2.2.2 on 2019-07-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0005_auto_20190703_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interactives',
            name='next_content',
        ),
        migrations.AddField(
            model_name='interactives',
            name='next_content',
            field=models.ManyToManyField(blank=True, null=True, related_name='_interactives_next_content_+', to='interactive.Interactives', verbose_name='下一个内容'),
        ),
    ]
