# Generated by Django 2.2.3 on 2019-08-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0008_auto_20190704_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactives',
            name='answer_type',
            field=models.IntegerField(choices=[(0, '单选'), (1, '多选'), (2, '填写内容')], default=0, verbose_name='答题类型'),
        ),
    ]
