# Generated by Django 2.2.3 on 2019-08-02 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0009_interactives_answer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactives',
            name='bible_contents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bible.Contents', verbose_name='引用经文'),
        ),
        migrations.AlterField(
            model_name='interactives',
            name='intermessage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interactive.InteractiveMessage', verbose_name='提示消息'),
        ),
        migrations.AlterField(
            model_name='interactives',
            name='new_contents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.Articles', verbose_name='引用新闻'),
        ),
    ]
