# Generated by Django 2.2.3 on 2019-08-03 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0011_auto_20190802_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interactives',
            name='next_content',
        ),
    ]
