# Generated by Django 2.2.3 on 2019-08-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0012_remove_interactives_next_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interactives',
            name='pre_content',
        ),
        migrations.AddField(
            model_name='interactives',
            name='pre_content',
            field=models.ManyToManyField(blank=True, null=True, related_name='_interactives_pre_content_+', to='interactive.Interactives', verbose_name='上一个内容'),
        ),
    ]
