# Generated by Django 2.2.3 on 2019-08-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0013_auto_20190803_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactives',
            name='pre_content',
            field=models.ManyToManyField(blank=True, related_name='_interactives_pre_content_+', to='interactive.Interactives', verbose_name='上一个内容'),
        ),
    ]
