# Generated by Django 2.2.3 on 2019-08-03 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0014_auto_20190803_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interactives',
            name='pre_content',
        ),
        migrations.AddField(
            model_name='interactives',
            name='pre_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subs', to='interactive.Interactives', verbose_name='上一个内容'),
        ),
    ]
