# Generated by Django 2.2.3 on 2019-08-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0015_auto_20190803_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactives',
            name='is_end',
            field=models.BooleanField(default=False, verbose_name='是否结束'),
        ),
        migrations.AlterField(
            model_name='interactives',
            name='content_type',
            field=models.IntegerField(choices=[(0, '只读内容'), (1, '问题内容'), (2, '选项内容')], default=2, verbose_name='内容类型'),
        ),
    ]
