# Generated by Django 2.2.3 on 2019-08-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0016_auto_20190804_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactiveclass',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='是否全部完成'),
        ),
    ]
