# Generated by Django 2.2.2 on 2019-07-04 10:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='等级名称')),
                ('lowerlimit', models.IntegerField(default=0, verbose_name='下限分数')),
                ('upperlimit', models.IntegerField(default=0, verbose_name='上限分数')),
                ('feedback', models.IntegerField(default=0, verbose_name='反馈贡献')),
                ('contribution', models.IntegerField(default=0, verbose_name='获得贡献值')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '用户等级',
                'verbose_name_plural': '用户等级',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contribution',
            field=models.IntegerField(default=0, verbose_name='贡献值'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='recommend',
            field=models.IntegerField(default=0, verbose_name='推荐人'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='score',
            field=models.IntegerField(default=0, verbose_name='得分'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserLevel', verbose_name='等级'),
        ),
    ]
