# Generated by Django 2.2.3 on 2019-08-04 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190704_1431'),
    ]

    operations = [

        migrations.AddField(
            model_name='userprofile',
            name='recommend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subs', to=settings.AUTH_USER_MODEL, verbose_name='推荐人'),
        ),
    ]
